import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import { InitialConfigType, InitialEditorStateType, LexicalComposer } from "@lexical/react/LexicalComposer";
import LexicalErrorBoundary from "@lexical/react/LexicalErrorBoundary";
import { HeadingNode, QuoteNode } from "@lexical/rich-text";
import { RichTextPlugin } from "@lexical/react/LexicalRichTextPlugin";
import { ContentEditable } from "@lexical/react/LexicalContentEditable";
import { HistoryPlugin } from '@lexical/react/LexicalHistoryPlugin';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const initialConfig: InitialConfigType = {
    namespace: "Editor",
    // theme,
    onError: console.error,
    nodes: [
      HeadingNode
    ],
    // editorState: initialEditorState,
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`} style={{border: "2px solid limegreen"}}>
          <div style={{border: "2px solid tomato"}}>
        <LexicalComposer initialConfig={initialConfig}>
          <RichTextPlugin
            contentEditable={<ContentEditable className="content-editable-root" />}
            placeholder={<div>Enter some text...</div>}
            ErrorBoundary={LexicalErrorBoundary}
            />
            <HistoryPlugin />
            {/* <MyCustomAutoFocusPlugin /> */}
        </LexicalComposer>
          </div>
      </main>
    </>
  );
}
